os: linux
dist: focal

language: generic

cache:
  pip: false
  directories:
  - "$HOME/db/"

env:
  global:
  - GIT_NAME: Spirillen
  #- GIT_EMAIL: "travis@travis-ci.org"
  - GIT_EMAIL: 44526987+spirillen@users.noreply.github.com
  - TRAVIS_REPO_SLUG: "${TRAVIS_REPO_SLUG}"
  - GIT_BRANCH: "${TRAVIS_BRANCH}"
  - TZ: UTC
  - PYFUNCEBLE_CONFIG_DIR: "${TRAVIS_BUILD_DIR}/.pyfunceble/"
  - PYFUNCEBLE_OUTPUT_LOCATION: "${TRAVIS_BUILD_DIR}/"
  - PYFUNCEBLE_AUTO_CONFIGURATION: yes
  - PYFUNCEBLE_DB_CHARSET="${DB_CHARSET}"
  - PYFUNCEBLE_DB_HOST="${DB_HOST}"
  - PYFUNCEBLE_DB_NAME="${DB_NAME}"
  - PYFUNCEBLE_DB_USERNAME="${DB_USERNAME}"
  - PYFUNCEBLE_DB_PASSWORD="${DB_PASSWORD}"
  - PYFUNCEBLE_DB_PORT="${DB_PORT}"
  #- PYFUNCEBLE_DEBUG: true
  #- PYFUNCEBLE_DEBUG_ON_SCREEN: true
  - PYTHON_VERSION: 3.9.0

addons:
  mariadb: '10.5'
  apt:
    packages:
    - dos2unix
    - msttcorefonts
    - lsof

install:
  - sudo bash "${TRAVIS_BUILD_DIR}/dev-tools/setup_recursor.sh"
  - export PATH="${HOME}/miniconda/bin:${PATH}"
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; else wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda create -q -n test-environment python="${PYTHON_VERSION}"
  - source activate test-environment
  - python --version --version
  - pip --version
  - conda --version
  - pip install --no-cache-dir --upgrade ultimate-hosts-blacklist-whitelist-dev dnspython[dnssec,idna]
  #- pip install --no-cache-dir -U git+https://github.com/funilrys/PyFunceble@rpz-syntax-check
  - pip install --no-cache-dir --upgrade pyfunceble-dev
  - rm miniconda.sh

git:
  depth: 2
#branches:
  #only:
  #- master
  #- pyfunceble-processing

script:
  #- sudo systemctl restart mysql.service
  #- sudo mysql -u root -h localhost -e "CREATE DATABASE ${DB_NAME} DEFAULT CHARACTER
  #  SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
  #- sudo mysql -u root -h localhost -e "CREATE USER 'root'@'%' IDENTIFIED BY ''"
  #- sudo mysql -u root -h localhost -e "CREATE USER '${DB_USERNAME}'@'localhost' IDENTIFIED
  #  BY '${DB_PASSWORD}';"
  #- sudo mariadb -u root -h localhost -e "GRANT ALL PRIVILEGES ON *.* TO '${DB_USERNAME}'@'localhost';"
  #- if [ -f ${HOME}/db/pyfunceble.sql ]; then sudo mariadb --user="${DB_USERNAME}" --password=${DB_PASSWORD}
  #  "${DB_NAME}" < ${HOME}/db/pyfunceble.sql; fi
  - bash dev-tools/PrepareData.sh && bash dev-tools/DataTesting.sh #&& sudo mkdir -p
  #  ${HOME}/db/ && sudo mariadb-dump --user="${DB_USERNAME}" --password="${DB_PASSWORD}" --opt "${DB_NAME}"
  #  > ${HOME}/db/pyfunceble.sql
 
