name: PyFunceble CI tests
on:
  push:
    branches:
      - "master"
      - "data-testing"
  pull_request:
    branches:
      - "master"

env:
  PYFUNCEBLE_AUTO_CONFIGURATION: "YES"
  GIT_NAME: "${{ secrets.GIT_BOT_NAME }}"
  GIT_EMAIL: "${{ secrets.GIT_BOT_EMAIL }}"
  PYFUNCEBLE_CONFIG_DIR: "${{ github.workspace }}/.pyfunceble"
  PYFUNCEBLE_OUTPUT_LOCATION: "${{ github.workspace }}/.pyfunceble"
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  BUILD_NUMBER: "${{ github.run_number }}"

jobs:
  test_and_push:
    name: Run PyFunceble against the files and push result to repository
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
          python_version:
            - "3.9.1"
          os:
            - ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        name: Clone repository
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install ldnsutils
        run: |
          DEBIAN_FRONTEND=noninteractive apt-get -y install ldnsutils

      - name: Install PyFunceble
        run: |
          pip install --no-cache-dir --pre PyFunceble-dev

      - name: Get PyFunceble version
        run: |
          PyFunceble --version

      - name: Install UHBW
        run: |
          pip install --no-cache-dir ultimate-hosts-blacklist-whitelist-dev

      - name: Get UHBW version
        run: |
          uhb_whitelist --version

      - name: Run Whitelist and prepare the test file
        run: |
          bash "${{ github.workspace }}/dev-tools/PrepareData.sh"

      - name: Run Data testing
        run: |
          bash "${{ github.workspace }}/dev-tools/DataTesting.sh"

      # - name: Run Data testing
      #   run: |
      #     pyfunceble --ci -q -h -ex --hierarchical --share-logs \
      #     --http --dots --autosave-minutes 15 \
      #     -f "${{ github.workspace }}/.pyfunceble/domains.txt"
