name: Launch a new test
on:
  schedule:
    - cron: "*/20 * * * *"

env:
  PYFUNCEBLE_AUTO_CONFIGURATION: "YES"
  GIT_NAME: "${{ secrets.GIT_BOT_NAME }}"
  GIT_EMAIL: "${{ secrets.GIT_BOT_EMAIL }}"
  PYFUNCEBLE_CONFIG_DIR: "${{ github.workspace }}/.pyfunceble"
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  scheduler:
    name: Trigger action
    runs-on: "${{ matrix.os }}"

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - "3.9.1"
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Clone repository
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Create local change
        run: |
          date +%s > "${{ github.workspace }}/.trigger"

      - name: Commit changes
        run: |
          git config --local user.email "$GIT_EMAIL"
          git config --local user.name "$GIT_NAME"
          git commit -m "Launch test" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
